name: apple-clang++

on:
  push:
    branches:
      - 'main'
      - 'testing/ci-clang'
  workflow_dispatch:
  pull_request:

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: macos-14

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/build \
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - working-directory: build/
        run: ./faker-cxx-UT
